#\u8BBE\u7F6Eip\u548C\u7AEF\u53E3\u53F7\uFF1A
#server.address=@server.address@
#server.address=172.21.0.3
server.address=10.43.27.231
#server.address=172.20.247.75
server.port=8089
#server.address=192.168.0.105
#server.address=172.26.193.231
#server.address=192.168.30.213
#server.address=192.168.0.104
#server.address=127.0.0.1
#server.address=0.0.0.0


server.servlet.session.timeout=7200

#Wserver.servlet.context-path=/a/b/c
#server.tomcat.basedir=@autojmeterpath@/pathparameter/

#spring.profiles.active=dev

#\u6D88\u8D39\u8005:consumer
dubbo.application.name=boot-order-service-consumer
#dubbo.registry.address=zookeeper://10.255.33.141:2181
#dubbo.registry.address=@dubbo.registry.address@
#dubbo.registry.address=zookeeper://192.168.88.217:2181
dubbo.registry.address=zookeeper://10.43.27.231:2181
#dubbo.registry.address=zookeeper://49.232.24.147:2181
dubbo.monitor.protocol=registry


autojmeterpath=/usr/local/jmeter
#autojmeterpath=/Users/dengdagui/Documents/install/maven


#Path.Parameters=@Path.Parameters@
Path.Parameters=${autojmeterpath}/pathparameter/


#\u63D0\u4F9B\u8005\uFF1Aprovider
#dubbo.protocol.name=dubbo
#dubbo.protocol.port=20880



# 网络接口配置
capture.interface=eth0

# 默认过滤规则（BPF语法）
capture.default-filter=tcp port 8080 or port 80

# 存储路径（如需保存pcap文件）
capture.save-path=/var/captures/




# 接口测试jmeter配置文件   
jmeter.load.run.Inter=Default
jmeterProperties.Inter=${autojmeterpath}/jmeter_inter/node_0/bin/jmeter.properties,${autojmeterpath}/jmeter_inter/node_1/bin/jmeter.properties
JVM_ARGS.inter_linux="-Xms1024m -Xmx1024m"
Heap.inter=-Xms1024m -Xmx1024m
#Heap.inter=@Heap.inter@
New.inter=-XX:NewSize=1024m -XX:MaxNewSize=1024m
jmeterStore.Inter=${autojmeterpath}/mars/jmeterStore/
jmeterScriptDir.Inter=${autojmeterpath}/mars/JmeterResultDir/jsp/result/test/jmeterScript/
resultReportDir.Inter=${autojmeterpath}/mars/ReportResultDir/
scriptDownLoadFromUrl.Inter=http://${server.address}:${server.port}/mars/images/initer/jmeterStore/
serverUrl.Inter=http://${server.address}:${server.port}/
ReporLinkstUrl.Inter=http://${server.address}:${server.port}/mars/ReportResultDir/
controllUpdateTimeServer.Inter=ntpdate us.pool.ntp.org


# 性能测试jmeter配置文件
jmeter.load.run=Default
jmeterProperties.Perf=${autojmeterpath}/jmeter_inter/node_2/bin/jmeter.properties
JVM_ARGS.perf_linux="-Xms2048m -Xmx2048m"
Heap.perf=-Xms1024m -Xmx1024m
#Heap.perf=@Heap.perf@
New.perf=-XX:NewSize=1024m -XX:MaxNewSize=1024m
jmeterStore=${autojmeterpath}/mars/jmeterStore/
jmeterScriptDir=${autojmeterpath}/mars/JmeterResultDir/jsp/result/test/jmeterScript/
resultReportDir=${autojmeterpath}/mars/ReportResultDir/
scriptDownLoadFromUrl=http://${server.address}:${server.port}/mars/images/perf/jmeterStore/
serverUrl.Perf=http://${server.address}:${server.port}/
ReporLinkst.Url=http://${server.address}:${server.port}/mars/ReportResultDir/
controllUpdateTimeServer=ntpdate us.pool.ntp.org




#邮箱 配置
mail.From=294332968@qq.com
mail.transport.protocol=smtp
mail.smtp.host=mail.ireadyit.com.com
mail.smtp.port=25
mail.smtp.auth=true
mail.debug=false

username=dengdagui@ireadyit.com.com
password=CC888cc

From=dengdagui@ireadyit.com.com
TO=dengdagui@ireadyit.com.com
CC=dengdagui@ireadyit.com.com
#597288934@qq.com
BCC=dengdagui@ireadyit.com.com