#SMTP\u90AE\u4EF6\u670D\u52A1\u5668:
#mail.transport.protocol=smtp
#mail.smtp.host=smtp.qq.com
#mail.smtp.port=465
#mail.smtp.auth=true
#mail.debug=true
#mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
#mail.smtp.socketFactory.port=465
#mail.smtp.socketFactory.fallback=false



#\u90AE\u4EF6\u670D\u52A1\u5668\u8BA4\u8BC1\u4FE1\u606F\uFF1A
#username=294332968@qq.com
#password=uewezorywyanbghg

#\u53D1\u4EF6\u4EBA
mail.From=294332968@qq.com
#\u6536\u4EF6\u4EBA
#TO=294332968@qq.com
#\u6284\u9001
#CC=294332968@qq.com
#597288934@qq.com
#\u5BC6\u9001
#BCC=294332968@qq.com



#----------------------------------------------------------
#SMTP\u90AE\u4EF6\u670D\u52A1\u5668:


mail.transport.protocol=smtp
mail.smtp.host=mail.ireadyit.com.com
mail.smtp.port=25
mail.smtp.auth=true
mail.debug=false

#\u90AE\u4EF6\u670D\u52A1\u5668\u8BA4\u8BC1\u4FE1\u606F\uFF1A
username=dengdagui@ireadyit.com.com
password=CC888cc


#\u53D1\u4EF6\u4EBA
From=dengdagui@ireadyit.com.com
#\u6536\u4EF6\u4EBA
TO=dengdagui@ireadyit.com.com
#\u6284\u9001
CC=dengdagui@ireadyit.com.com
#597288934@qq.com
#\u5BC6\u9001
BCC=dengdagui@ireadyit.com.com