
#\u8BBE\u7F6Eip\u548C\u7AEF\u53E3\u53F7\uFF1A
#server.address=@{server.address}@

#\u6307\u5B9A\u8D1F\u8F7D\u673A\u8FD0\u884C\u6A21\u5F0F\uFF1A
#此参数以废弃
jmeter.load.run.Inter=Default
#jmeter.load.run.Inter=-R 10.255.6.107
#jmeter.load.run.Inter=-R
#jmeter.load.run.Inter=-H 10.255.6.107 -P 11009
#jmeter.load.run.Inter=-H my.proxy.server -P 8000 -u username -a password -N localhost


#JmeterAgent  \u4E3B\u52A8\u914D\u7F6EIp\uFF1A

#以下内容是不要的，方便调试而设置的参数：
jmeterAgent.IP.Inter=10.255.33.72,10.255.33.71
interfaceconfig.properties=10.255.33.72,10.255.33.71
jmeterProperties.Inters=10.255.33.72,10.255.33.71


#JmeterProperties \u591A\u4E2Ajmeter\u63A7\u5236\u53F0,\u6027\u80FD\u6D4B\u8BD5\u5E76\u53D1\uFF1A
#jmeterProperties.Inter=D:/jmeter4.0/apache-jmeter-4.0/bin/jmeter.properties,D:/jmeter4.0/node_1/bin/jmeter.properties,D:/jmeter4.0/node_2/bin/jmeter.properties,D:/jmeter4.0/node_3/bin/jmeter.properties,D:/jmeter4.0/node_4/bin/jmeter.properties,D:/jmeter4.0/node_5/bin/jmeter.properties
#jmeterProperties.Inter=D:/jmeter4.0/node_1/bin/jmeter.properties,D:/jmeter4.0/node_0/bin/jmeter.properties
#jmeterProperties.Inter=@jmeterProperties.Inter@
#jmeterProperties.Inter=/usr/local/jmeter/jmeter_inter/node_0/bin/jmeter.properties,/usr/local/jmeter/jmeter_inter/node_1/bin/jmeter.properties,/usr/local/jmeter/jmeter_inter/node_2/bin/jmeter.properties,/usr/local/jmeter/jmeter_inter/node_3/bin/jmeter.properties,/usr/local/jmeter/jmeter_inter/node_4/bin/jmeter.properties,/usr/local/jmeter/jmeter_inter/node_5/bin/jmeter.properties
#jmeterProperties.Inter=/usr/local/jmeter/jmeter_inter/node_0/bin/jmeter.properties
jmeterProperties.Inter=${autojmeterpath}/jmeter_inter/node_0/bin/jmeter.properties
#\u8FD0\u884C\u65F6\u8BBE\u7F6E\u5185\u5B58\u5927\u5C0F\uFF1A

JVM_ARGS.inter_linux="-Xms1024m -Xmx1024m"


Heap.inter=-Xms1024m -Xmx1024m
#Heap.inter=@Heap.inter@
New.inter=-XX:NewSize=1024m -XX:MaxNewSize=1024m


#New.inter=@New.inter@

#\u6027\u80FD\u6D4B\u8BD5\u811A\u672C\u5B58\u653E\u76EE\u5F55\uFF1A
#jmeterStore.Inter=D:/mars/jmeterStore/
#jmeterStore.Inter=@jmeterStore.Inter@
jmeterStore.Inter=${autojmeterpath}/mars/jmeterStore/
#jmeterStore.Inter=/usr/local/jmeter/mars/jmeterStore/

#\u751F\u6210\u63A5\u53E3\u6D4B\u8BD5\u811A\u672C\u76EE\u5F55\uFF1A
#jmeterScriptDir.Inter=D:/mars/JmeterResultDir/jsp/result/test/jmeterScript/
#jmeterScriptDir.Inter=@jmeterScriptDir.Inter@
#jmeterScriptDir.Inter=/usr/local/jmeter/mars/JmeterResultDir/jsp/result/test/jmeterScript/
jmeterScriptDir.Inter=${autojmeterpath}/mars/JmeterResultDir/jsp/result/test/jmeterScript/
#\u751F\u6210\u63A5\u53E3\u6D4B\u8BD5\u62A5\u544A\u76EE\u5F55\uFF1A

#resultReportDir.Inter=@resultReportDir.Inter@
#resultReportDir.Inter=/usr/local/jmeter/mars/ReportResultDir/
resultReportDir.Inter=${autojmeterpath}/mars/ReportResultDir/
#jmeter\u7684agent\u4E0B\u8F7D\u811A\u672C\u5730\u5740\uFF1A
#scriptDownLoadFromUrl.Inter=http://192.168.88.217:8089/mars/images/initer/jmeterStore/
#scriptDownLoadFromUrl.Inter=http://192.168.88.217:8089/mars/images/initer/jmeterStore/

scriptDownLoadFromUrl.Inter=http://${server.address}:${server.port}/mars/images/initer/jmeterStore/
#scriptDownLoadFromUrl.Inter=@scriptDownLoadFromUrl.Inter@
#\u57DF\u540D\uFF1A
#serverUrl.Inter=https://test-mars.ucredit.com/mars/
#serverUrl.Inter=http://192.168.88.217:8089/
#serverUrl.Inter=http://192.168.88.217:8089/
serverUrl.Inter=http://${server.address}:${server.port}/
#serverUrl.Inter=@serverUrl.Inter@

#\u62A5\u544A\u8D85\u94FE\u63A5\uFF0C\u4FBF\u4E8E\u67E5\u770Bjtl\u4E0Eindex\u65E5\u5FD7\u4FE1\u606F\uFF1A
#ReporLinkstUrl.Inter=https://test-mars.ucredit.com/mars/images/initer/ReportResultDir/
#ReporLinkstUrl.Inter=http://192.168.88.217:8089/mars/ReportResultDir/
#ReporLinkstUrl.Inter=http://192.168.88.217:8089/mars/ReportResultDir/
ReporLinkstUrl.Inter=http://${server.address}:${server.port}/mars/ReportResultDir/
#ReporLinkstUrl.Inter=@ReporLinkstUrl.Inter@

# \u63A7\u5236\u53F0\u540C\u6B65\u65F6\u95F4\u670D\u52A1\u5668\uFF1A
controllUpdateTimeServer.Inter=ntpdate us.pool.ntp.org
#controllUpdateTimeServer.Inter=@controllUpdateTimeServer.Inter@



#DEFAULT_USER.Inter=admin
#DEFAULT_PASSWORD.Inter=admin
#DEFAULT_BROKER_URL.Inter=tcp://10.255.33.141:61616
#TOPIC.TOPIC_NAME.Inter=testSpringTopic

