
#此参数以废弃
jmeter.load.run=Default
#jmeter.load.run=-R 10.255.6.107
#jmeter.load.run=-R 10.255.33.72,10.255.33.71
#jmeter.load.run=-R  10.255.33.72
#jmeter.load.run=-H 10.255.6.107 -P 11009
#jmeter.load.run=-H my.proxy.server -P 8000 -u username -a password -N localhost


jmeterProperties.Perf=${autojmeterpath}/jmeter_inter/node_0/bin/jmeter.properties,/usr/local/jmeter/jmeter_inter/node_1/bin/jmeter.properties


JVM_ARGS.perf_linux="-Xms2048m -Xmx2048m"
#JVM_ARGS.perf_linux=@VM_ARGS.perf_linux@
Heap.perf=-Xms1024m -Xmx1024m
#Heap.perf=@Heap.perf@
New.perf=-XX:NewSize=1024m -XX:MaxNewSize=1024m

jmeterStore=${autojmeterpath}/mars/jmeterStore/


jmeterScriptDir=${autojmeterpath}/mars/JmeterResultDir/jsp/result/test/jmeterScript/


resultReportDir=${autojmeterpath}/mars/ReportResultDir/


scriptDownLoadFromUrl=http://${server.address}:${server.port}/mars/images/perf/jmeterStore/

serverUrl.Perf=http://${server.address}:${server.port}/

ReporLinkst.Url=http://${server.address}:${server.port}/mars/ReportResultDir/
#ReporLinkst.Url=@ReporLinkst.Url@
#10.255.6.23

#\u63A7\u5236\u53F0\u540C\u6B65\u65F6\u95F4\u670D\u52A1\u5668\uFF1A
controllUpdateTimeServer=ntpdate us.pool.ntp.org
#controllUpdateTimeServer=@controllUpdateTimeServer@

