#\u670D\u52A1\u5668\u7AEF\u53E3
host.ip=10.43.27.231
server.port=8082
dubbo.protocol.port=20882

zookeeper.address=10.43.27.231:2181
#zookeeper.address=172.21.152.95:2181
#zookeeper.address=49.232.24.147:2181

#\u8D1F\u8F7D\u673A\u811A\u672C\u4E0B\u8F7D\u5730\u5740
#agentDownStore=d:/resource/images/

#agentDownStore=d:/resource/images/
agentDownStore=/usr/local/jmeter/agent/inter/agentDownStore


#agentjmeterProperties=D:/jmeter4.0/node_1/bin/jmeter.properties
agentjmeterProperties=/usr/local/jmeter/agent/inter/bootServiceProvide/apache-jmeter-5.6.3/bin/jmeter.properties


#\u65F6\u95F4\u540C\u6B65\u670D\u52A1\u5668
agentUpdateTimeServer=ntpdate us.pool.ntp.org

#\u8BBE\u7F6E\u8FD0\u884C\u5185\u5B58\u5927\u5C0F
JVM_ARGS.agent_linux=-Xms512m -Xmx512m
Heap.agent=-Xms512m -Xmx1000m
New.agent=-XX:NewSize=512m -XX:MaxNewSize=512m

#\u8BBE\u7F6Ejmeter\u7684\u8FD0\u884C\u7C7B\u578B\uFF1A[Perf/Inter]
jmeter.run.type=Inter



